### ISSUE TITLE
Can not extract "visible masks"

### ISSUE THREAD

**Issue by binh0804** [trqminh/aistron#5]
I am training on my own dataset but when I run inference, only pred_masks property have value (but fortunately it still amodal masks). Other properties, **pred_amodal_masks, visible_masks, occluding_masks** just only []  -> empty polygons. Is there any secret to train on custom dataset?

**Comment by trqminh** [comment]
Hi @binh0804. Thank you for your interest in our work! 
What method did you use to train? I guess you're using MaskRCNN. If that is the case, maskrcnn won't output pred_amodal_masks, visible_masks, occluding_masks
